# Stubs for demo (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Callable, Mapping, Sequence, TypeVar

DB_NAME: Any

def twice(i: int, next: Callable[[int], int]) -> int: ...
def add(i: int) -> int: ...
T = TypeVar('T')

def first(seq: Sequence[T]) -> T: ...

p: Any
q: Any
Movie: Any
movie: Movie
c: Any

def print_typed_dict(obj: Mapping[str, object]) -> None: ...
